### ISSUE TITLE
Use our team's `.prettierrc.yaml`

### ISSUE THREAD

**Issue by NatoBoram** [Ayazi01/NEWS-SveltKit-APP#17]
Just to get used to it :)

We made a Prettier config a little while ago for Svelte+Tailwind when we started the UI-Team. It has a little bit of everyone in it.

```yaml
arrowParens: avoid
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
pluginSearchDirs:
  - '.'
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
printWidth: 100
semi: false
singleQuote: true
trailingComma: all
useTabs: true
```
